### PR TITLE
Added/updated icons

### PR DESCRIPTION
**Pull request by yaomtc**

### CODE REVIEW

**Review by simonpoole — CHANGES_REQUESTED** [review]
thanks and great that you are contributing!

Two notes: 

- the PNG version of the icons are not necessary, they will be generated during the build process, and I'll commit them then (they are really only in the repo for historical reasons),
- the background coloring of the icons depends with the exception of those located in svg-signs (which are used as they are) on the sub-directory they are located in, so building-school.svg should be in svg-osm-icons/man_made/ not in a separate new directory.

**Comment by yaomtc** [comment]
Good to know I won't have to export the PNGs, that will save time. I've made the changes.

**Comment by yaomtc** [comment]
Tweaked some icons for better visibility/clarity. Thoughts?

Also, I'm not sure what icons are missing, how would I go about finding that?

**Comment by simonpoole** [comment]
> Tweaked some icons for better visibility/clarity. Thoughts?
> 
> Also, I'm not sure what icons are missing, how would I go about finding that?

Sorry, I've been wanting to get back to you, but have been busy.

Wrt the first lot of icons, was your intention to replace the existing bus lane icon (yours is definitely better)? If yes you should be using the original name to reduce friction. 

Missing icons: to support multiple different sets of icons I'm employing an additional level of redirection, the references in the preset file, for example https://github.com/simonpoole/beautified-JOSM-preset/blob/master/master_preset.xml#L3660, points to an entry in https://github.com/simonpoole/beautified-JOSM-preset/blob/master/beautified_icons.txt#L200 If the entry there doesn't reference an actual icon or refers to an "empty" icon that is missing. https://github.com/simonpoole/beautified-JOSM-preset/issues/4 has a historic list of missing icons, but you will need to check (because_historic_ :-)) if that is actually still the case.

### Working on an OSS project with github 

It seems as if you are uploading/modifying the files directly via the github website. That is not a good idea, particularly if you are making a number of changes / actively working on the branch, You should be using git either on command line or in an IDE. https://github.com/asmeurer/git-workflow outlines how that works. What that text doesn't say are the following three points: 

#### Create a new branch / PR for new work
Create a new PR for new work (for example in your case I would suggest 1 PR per icon or per related changes), If necessary you can create a new branch and 'copy' commits there by cherry picking (see for example https://docs.gitlab.com/ee/topics/git/cherry_picking.html). This is typically far simpler to do in an IDE, but YMMV.

#### Squash away noise
If you are fixing a typo, a mistake or whatever, _squash_ the relevant commits (for example you would squash the commits deleting the unnecessary PNG icons with the respective commits in which you added them), then _force_ push your work to your branch on github (https://docs.gitlab.com/ee/topics/git/git_rebase.html covers a lot of this),

#### Rebase 
The maintainer of a project may ask you to _rebase_ your branch before they will merge it (see the above linked documentation), this essentially changes your commits to be chronologically after any work that has been committed while you have been working on your branch. Besides looking a lot neater in the commit history, it has the advantage that you get to figure out how your changes need to be modified to fit to the changed code (if something relevant has changed that causes a conflict), and doesn't force the maintainer to 2nd guess you.

This will all sound a bit complicated but it is actually easier and less work for all involved parties once you've got used to it.

**Comment by yaomtc** [comment]
Cleaned it up a bit with Github Desktop. How's that?

**Comment by yaomtc** [comment]
Also added another icon. 

If I push a change, and then change something with what I changed and have another commit for the same file, should I generally squash them? Altering recent history shouldn't be a big deal on my own personal branch, right?

**Comment by simonpoole** [comment]
> Also added another icon.
> 
> If I push a change, and then change something with what I changed and have another commit for the same file, should I generally squash them? Altering recent history shouldn't be a big deal on my own personal branch, right?

Yes in general altering history local, and in the branch the pull request is based on is no, problem even expected to happen if it is something more complex. In general you would want to avoid changing the history of anything that has multiple people working on it/using it as that tends to cause a lot of pain. That pain is what the "github workflow" with one branch per pull request and then merging that in to the target development branch (most of the time main or master) avoids.

**Comment by simonpoole** [comment]
Merged with https://github.com/simonpoole/beautified-JOSM-preset/commit/1d2a0d7567785da94adaca114d659dfaed6e64cf Thanks!

**Pull request closed without merging**
