### PR TITLE
Landuse recreational dog

### PR DESCRIPTION
**Pull request by ltog**
This PR contains the following changes:

1. Move `dog=*` into its own chunk.
2. Add `dog=*` to `landuse=recreation_ground`
3. Remove `dog=official` since there are 0 uses for it according to [TagInfo](https://taginfo.openstreetmap.org/keys/dog#values) (IMHO we could reduce the set of available values even more...)

For reference check https://wiki.openstreetmap.org/wiki/Key:dog

### CODE REVIEW

**Comment by simonpoole** [comment]
Shouldn't this be https://wiki.openstreetmap.org/wiki/Tag:leisure%3Ddog_park ?

**Comment by ltog** [comment]
@simonpoole : In this PR I want users to give the possibility to extend existing `landuse=recreation_ground` with the information whether dogs are allowed in these areas. Tagging them as `leisure=dog_park` might be inappropriate, especially if dogs are not allowed. So for me, these are two different concepts and adding the dog accessibility information seems to be a useful addition to the recreation grounds to me.

**Comment by simonpoole** [comment]
Ah, I misunderstood the purpose of the PR, sorry. 

IMHO Yes, Leashed, No would however seem to be sufficient values (these tend to be copy/pasted from other access tags, but some of them don't really make sense.

**Comment by simonpoole** [comment]
@ltog could you rebase this?

**Comment by ltog** [comment]
Argh, seems not that easy...

Note to self: Try to cherry-pick these commits (from top of list to bottom):

276fcd7
915a6e4
a32c6fd

**Comment by ltog** [comment]
This PR is outdated. Instead, https://github.com/simonpoole/beautified-JOSM-preset/pull/272 should be used.

**Pull request closed without merging**
