### PR TITLE
Added material-tag to wayside_cross

### PR DESCRIPTION
**Pull request by morray**

### CODE REVIEW

**Comment by simonpoole** [comment]
Thanks. Could you squash all the commits in to one and then force push? See https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by morray** [comment]
> Thanks. Could you squash all the commits in to one and then force push? See https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

can this be done in some way directly on the github webpage? I only find reverence to do it automatically while merging the pull request`?

**Comment by simonpoole** [comment]
I can do it, just wanted to give you the opportunity to do it yourself.

**Comment by simonpoole** [comment]
Merged in https://github.com/simonpoole/beautified-JOSM-preset/commit/448977777d4cd74607fd2bfc27cc6654fffd42b9

**Pull request closed without merging**
