### PR TITLE
Fix whitespace

### PR DESCRIPTION
**Pull request by ltog**
The file `master_preset.xml` had several whitespace issues:

- Sometimes tabs were used instead of spaces
- Sometimes there were spaces at the end of lines

This PR tries to fix these issues. The indentation is still inconsistent, however.

One could try to run `xmllint` or similar over it, but I didn't do that (yet).

### CODE REVIEW

**Comment by simonpoole** [comment]
Lukas can you rebase this on the current head of master?

**Comment by simonpoole** [comment]
> 
> 
> Lukas can you rebase this on the current head of master?

@ltog ping, alternatively you can allow me to push to your PRs.

**Comment by ltog** [comment]
@simonpoole : Sorry, I didn't find the time yet to look at it...

There is already a checked checkbox `Allow edits and access to secrets by maintainers` set in this PR. Did you mean this setting or something else?

**Comment by simonpoole** [comment]
The "allow edits" is the one, see https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by ltog** [comment]
@simonpoole : Ok, it seems the setting was slightly renamed. It was activated by me since I opened the PR. I'd be happy if you could rebase this PR.

On a sidenote: AFAIR the other PRs are NOT dependent on this one, so most of them should be mergeable.

**Comment by simonpoole** [comment]
Merged with https://github.com/simonpoole/beautified-JOSM-preset/commit/32a086a9e6b9c6a3b2b52346e1d36c1d04f34df0

**Pull request closed without merging**
