### PR TITLE
Update parking type

### PR DESCRIPTION
**Pull request by Mannivu**
Add street side as a suitable parking type (the tag has been recently [approved](https://wiki.openstreetmap.org/wiki/Proposed_features/parking%3Dstreet_side)).

### CODE REVIEW

**Comment by simonpoole** [comment]
Sorry for the late response, I wanted to merge this before Christmas, however something is weird about the PR. Could you rebase on the current master? Thanks.

**Comment by Mannivu** [comment]
I've updated my branch, should be fine now.

**Comment by simonpoole** [comment]
You shouldn't be merging your changes, you should be rebasing your branch on to master. When I then merge the PR your commits will get merged.

**Comment by Mannivu** [comment]
I've made a mess. I'll delete my branch and redo the edit. Sorry.

**Pull request closed without merging**
